version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
   build: ./NodeJS
   container_name: backend
   ports:
     - "3000:3000"
   environment:
     - MONGODB_URI=mongodb://mongodb:27017/employeedb
   depends_on:
     - mongodb

  frontend:
    build: ./Angularapp
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
